// Aqui ponemos nuestros types definidos en costantes para evitar
//errores de tipeo
 export const ADD_POKEMONS = 'ADD_POKEMONS'
 export const GET_POKEMON_BY_ID = 'GET_POKEMONS'
 export const SET_ORDER_A_Z = 'SET_ORDER_A_Z'
 export const SET_ORDER_Z_A = 'SET_ORDER_Z_A'
 export const FILTER_BY_ATTACK_MAX_MIN = 'FILTER_BY_ATTACK_MAX_MIN'
 export const FILTER_BY_ATTACK_MIN_MAX = 'FILTER_BY_ATTACK_MIN_MAX'
 export const SHOW_API_POKEMONS = 'SHOW_API_POKEMONS'
 export const SHOW_DB_POKEMONS = 'SHOW_DB_POKEMONS'
 export const SHOW_ALL_POKEMONS = 'SHOW_ALL_POKEMONS'
 export const GET_POKEMONS_TYPE = 'GET_POKEMONS_TYPE'
 export const SET_POKEMONS_TYPE_RENDER = 'SET_POKEMONS_TYPE_RENDER'
 export const GET_POKEMON_PER_NAME = 'GET_POKEMON_PER_NAME'
 export const ORDER_DEFAULT = 'ORDER_DEFAULT'